# cfgs/train.yaml
note: MobileNetV4, with ForwardDynamicsModel

logging:
  log_wandb: true
  wandb_group: saccadic_jepa
  wandb_sweep:
  log_every: 1
  save_every_n_epochs: 10
  tqdm_silent: false
meta:
  device: "cuda"
  model_folder: 
  load_model: false
  enable_eval: true
  eval_every_n_epochs: 5
  seed: 1
data:
  env_name: imagenet_patches
  dataset_path: "~/datasets/vision/imagenet"
  img_size: 320
  crop_size: 128
  batch_size: 1024
  num_workers: 16
  pin_mem: true
  persistent_workers: true
training:
  use_amp: true
  dtype: bfloat16
model:
  compile: false
  encoder_architecture: mobilenetv2
  idm:
    hidden_dim: 1024
  predictor:
    hidden_dim: 1024
  regularizer:
    type: vicreg  # vicreg, sigreg
    # bcs_scoeff: 10.0
    cov_coeff: 8.0
    std_coeff: 16.0
    idm_coeff: 1.0
    pred_coeff: 1.0
    use_proj: false
    idm_after_proj: false
optim:
  epochs: 300
  lr: 1.e-4
  enc_lr: 1.e-4
  proj_lr: 1.e-4
  pred_lr: 1.e-4
  idm_lr: 1.e-4
  grad_clip_enc: 20.0
  grad_clip_proj: 20.0
  grad_clip_pred: 20.0
  grad_clip_idm: 20.0
  weight_decay: 0.0
eval:
  batch_size: 512
  candidate_stride: 32
  refine_iters: 3
  refine_window: 1